import Config

# Codepagex compiles its mapping tables; only the ones a shell's output can
# plausibly arrive in are worth the beam size. These are the Windows OEM/ANSI
# codepages (`chcp` numbers): PC/* is the OEM family, WINDOWS/* the ANSI one.
config :codepagex, :encodings, ~w(
    VENDORS/MICSFT/PC/CP437
    VENDORS/MICSFT/PC/CP850
    VENDORS/MICSFT/PC/CP866
    VENDORS/MICSFT/WINDOWS/CP1250
    VENDORS/MICSFT/WINDOWS/CP1251
    VENDORS/MICSFT/WINDOWS/CP1252
    VENDORS/MICSFT/WINDOWS/CP1253
    VENDORS/MICSFT/WINDOWS/CP1254
    VENDORS/MICSFT/WINDOWS/CP1255
    VENDORS/MICSFT/WINDOWS/CP1256
    VENDORS/MICSFT/WINDOWS/CP1257
    VENDORS/MICSFT/WINDOWS/CP1258
    VENDORS/MICSFT/WINDOWS/CP932
    VENDORS/MICSFT/WINDOWS/CP936
    VENDORS/MICSFT/WINDOWS/CP949
    VENDORS/MICSFT/WINDOWS/CP950
  )
